apiVersion: v1
kind: Pod
metadata:
  name: exa-frontend-p
  labels:
    access-exa: "true"
spec:
  containers:
    - image: docker.io/deutschmann/exa-frontend
      name: exa-frontend
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
      env:
        - name: FLASK_DEBUG
          value: "1"
        - name: BACKEND_NAME
          value: "exa-backend" # the backend service
        - name: BACKEND_PORT
          value: "80" # the port on which the backend listens on the service
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
  automountServiceAccountToken: false # no service account needed