# Source: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exa-backend-read-pods
subjects:
- kind: ServiceAccount
  name: exa-backend-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io