# Source: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rs-admin
rules:
- apiGroups: ["extensions", "apps"] # "" indicates the core API group
  resources: ["replicasets"]
  verbs: ["get", "watch", "list", "scale"]