apiVersion: v1
kind: Pod
metadata:
  name: exa-backend-p
  labels:
    app: exa-backend
spec:
  containers:
    - image: docker.io/deutschmann/exa-backend
      name: exa-backend
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      env:
        - name: FLASK_DEBUG
          value: "1"
        - name: LOCAL_CLUSTER
          value: "0"
  serviceAccountName: exa-backend-sa