# Source: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: rs-admin
rules:
- apiGroups: ["extensions", "apps"] # "" indicates the core API group
  resources: ["replicasets", "replicasets.apps"]
  verbs: ["get", "watch", "list", "scale"]