kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: exa-backend-policy
spec:
  podSelector:
    matchLabels:
      app: exa-backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access-exa: "true"