apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - image: docker.io/deutschmann/my-app
      name: my-app
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
      volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: secrets
      secret:
        secretName: my-secret
