apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - image: docker.io/deutschmann/my-app
      name: my-app
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
  imagePullSecrets:
    - name: regcred
