# Source: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exa-backend-admin-replicasets
  namespace: default
subjects:
- kind: ServiceAccount
  name: exa-backend-sa 
  namespace: default
roleRef:
  kind: Role
  name: rs-admin
  apiGroup: rbac.authorization.k8s.io