apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exa-rolebinding-psp
  namespace: default # TODO change to admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exa-role-restricted-psp
subjects:
- kind: User
  name: gke_bachelor-kubernetes-security_europe-west2-a_thunder # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
- kind: ServiceAccount # Omit apiGroup
  name: default
  namespace: default
- kind: ServiceAccount # Omit apiGroup
  name: exa-backend-sa
  namespace: default