apiVersion: v1
kind: Pod
metadata:
  name: alpaca-prod
  labels:
        app: alpaca
        ev: prod
        ver: "1"
spec:
  replicas: 3
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: alpaca-prod
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3